**Fancy Indexing**

In [ ]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[0,0,3])

5


In [ ]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[[0],[0],[3]])

[5]


In [ ]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[[0,0,1],[0,1,0],[3,1,2]])

[ 5 22 25]


SORTING

In [ ]:
import numpy as np

a = np.array([1,3,4,5,5])

a.sort()


print(a)

[1 3 4 5 5]


In [ ]:
import numpy as np

x = np.array([1,3,4,5,5])

y = np.sort(x)[::-1]


print(y)

[5 5 4 3 1]


In [ ]:
import numpy as np

x = np.array([[1,3,4,5,5],[12,22,45,77,66]])

x.sort()


print(x)

[[ 1  3  4  5  5]
 [12 22 45 66 77]]


In [ ]:
import numpy as np

x = np.array([[1,3,4,5,5],[12,22,45,77,66]])

x = np.sort(x,axis=1)


print(x)

[[ 1  3  4  5  5]
 [12 22 45 66 77]]


In [ ]:
import numpy as np

x = np.array([[1,3,4,5,5],[12,22,45,77,66]])

x = np.sort(x,axis=0)


print(x)

[[ 1  3  4  5  5]
 [12 22 45 77 66]]


In [ ]:
import numpy as np

x = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

x = np.sort(x,axis=0)


print(x)

[[[ 1  3  4  5  5]
  [12 22 45 66 66]]

 [[ 1 14 25 17 88]
  [33 44 55 77 77]]]


In [ ]:
import numpy as np

x = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(x.ndim)
x = np.sort(x,axis=1)


print(x)

3
[[[ 1  3  4  5  5]
  [12 22 45 77 66]]

 [[ 1 14 25 17 77]
  [33 44 55 66 88]]]


In [ ]:
#copy and view

import numpy as np

x = np.array([1,3,48,5,55])

y = x

z = x.copy()         #deep copy
w = x.view()         #shallow copy


print(x)
print(y)
print(z)
print(w)

x[2] = 465

print(x)
print(y)
print(z)
print(w)

[ 1  3 48  5 55]
[ 1  3 48  5 55]
[ 1  3 48  5 55]
[ 1  3 48  5 55]
[  1   3 465   5  55]
[  1   3 465   5  55]
[ 1  3 48  5 55]
[  1   3 465   5  55]


In [ ]:
#reshape,resize,flatten

import numpy as np

a = np.arange(16)




print(a)

print(a.shape)

b = a.reshape(2,8)

b



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
b = a.reshape(4,4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:


import numpy as np

a = np.arange(16)




print(a)

print(a.shape)

b = a.reshape(4,5)

b


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


ValueError: cannot reshape array of size 16 into shape (4,5)

In [ ]:
#reshape,resize,flatten

import numpy as np

a = np.arange(16)


print(a)

print(a.shape)

b = a.resize(4,5)

b
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15,  0,  0,  0,  0]])

In [ ]:
import numpy as np

a = np.arange(16)


print(a)

print(a.shape)

b = a.resize(4,10)

b
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
import numpy as np

a = np.array([[2,3,4],[4,5,6]])


print(a)

b  = a.flatten()

print(b)



[[2 3 4]
 [4 5 6]]
[2 3 4 4 5 6]


In [ ]:
import numpy as np

a = np.array([[2,3,4],[4,5,6]])

b = np.array([[2,3,4],[4,2,4],[4,2,4]])



print(a)

print('*' * 30)

print(b)

print('*' * 30)

print(np.dot(a,b))



[[2 3 4]
 [4 5 6]]
******************************
[[2 3 4]
 [4 2 4]
 [4 2 4]]
******************************
[[32 20 36]
 [52 34 60]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,5,6]],[[2,3,4],[4,2,4]]])

b = np.array([[[2,3,4],[4,2,4],[4,2,4]],[[2,3,4],[4,5,6],[4,2,4]]])



print(a)

print('*' * 30)

print(b)

print('*' * 30)

print(np.dot(a,b))



[[[2 3 4]
  [4 5 6]]

 [[2 3 4]
  [4 2 4]]]
******************************
[[[2 3 4]
  [4 2 4]
  [4 2 4]]

 [[2 3 4]
  [4 5 6]
  [4 2 4]]]
******************************
[[[[32 20 36]
   [32 29 42]]

  [[52 34 60]
   [52 49 70]]]


 [[[32 20 36]
   [32 29 42]]

  [[32 24 40]
   [32 30 44]]]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])




print(a)

print('*' * 30)

print(np.min(a))

print(np.min(a,axis = 0))



[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[2 1 4]
 [4 0 4]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])




print(a)

print('*' * 30)

print(np.min(a))

print(np.min(a,axis = 1))



[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[2 1 4]
 [2 0 4]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])




print(a)

print('*' * 30)

print(np.min(a))

print(np.min(a,axis = 2))



[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[2 1]
 [1 0]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])




print(a)

print('*' * 30)

print(np.min(a))

print(np.min(a))
print(np.max(a,axis = 2))



[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
0
[[4 4]
 [4 4]]


In [ ]:
import numpy as np

a = np.array([[[2,3,4],[4,1,4]],[[2,1,4],[4,0,4]]])




print(a)

print('*' * 30)

print(np.min(a))

print(np.mean(a,axis = 2))



[[[2 3 4]
  [4 1 4]]

 [[2 1 4]
  [4 0 4]]]
******************************
0
[[3.         3.        ]
 [2.33333333 2.66666667]]


**ARRAY JOINING**

In [ ]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.vstack((a,b))

c

array([[ 3,  4,  2],
       [ 4,  5,  3],
       [ 4,  3,  1],
       [ 5, 32,  0]])

In [ ]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.row_stack((a,b))

c

array([[ 3,  4,  2],
       [ 4,  5,  3],
       [ 4,  3,  1],
       [ 5, 32,  0]])

In [ ]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.hstack((a,b))

c

array([[ 3,  4,  2,  4,  3,  1],
       [ 4,  5,  3,  5, 32,  0]])

In [ ]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

c = np.column_stack((a,b))

c

array([[ 3,  4,  2,  4,  3,  1],
       [ 4,  5,  3,  5, 32,  0]])

In [ ]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

x = np.concatenate((a,b))

x


array([[ 3,  4,  2],
       [ 4,  5,  3],
       [ 4,  3,  1],
       [ 5, 32,  0]])

In [ ]:
import numpy as np

a = np.array([(3,4,2),(4,5,3)])

b = np.array([(4,3,1),(5,32,0)])

x = np.concatenate((a,b),axis = 1)

x


array([[ 3,  4,  2,  4,  3,  1],
       [ 4,  5,  3,  5, 32,  0]])